config/routes.rb
Rails.application.routes.draw do

  localized do
    # rest
    resources :censos
    resources :people
    resources :certificates
    resources :votes
    resources :candidates
    resources :elections
    resources :request_censos
    resources :contacts, only: %i[new index create]

    # routes with only a member
    resources :announcements do
      delete 'remove_olds', on: :collection
    end

    resources :events do
      delete 'remove_olds', on: :collection
    end

    # routes for events
    resources :newsletters do
      post 'deliver', on: :member
    end

    # single routes

    get 'residences/index'

    # routes with namespace
    namespace :statistics do
      get 'total', 'average', 'health', 'gender', 'health', 'censo_date', 'children'
    end

    # routes devise
    devise_for :users

    # root
    root to: 'home#index'
  end

  namespace :users do
    namespace :omniauth_callbacks do
      get 'facebook', 'google_oauth2', 'twitter'
    end
  end

  devise_scope :user do
    namespace :users do
      scope 'auth' do
        get 'facebook/callback', to: 'omniauth_callbacks#facebook'
        get 'google_oauth2/callback', to: 'omniauth_callbacks#google_oauth2'
        get 'twitter/callback', to: 'omniauth_callbacks#twitter'
      end
    end
  end
end

app/models/newsletter.rb
# == Schema Information
#
# Table name: newsletters
#
#  id         :integer          not null, primary key
#  subject    :string
#  content    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Newsletter < ApplicationRecord
  belongs_to :user

  validates :subject, :content, presence: true
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :set_newsletter, only: [:show, :edit, :update, :destroy]

  # GET /newsletters
  # GET /newsletters.json
  def index
    @newsletters = Newsletter.all
  end

  # GET /newsletters/1
  # GET /newsletters/1.json
  def show
  end

  # GET /newsletters/new
  def new
    @newsletter = Newsletter.new
  end

  def deliver
    @newsletter = Newsletter.find(params[:id])
    # the next line is executed asynchronously
    UserMailer.newsletter(@newsletter).deliver_later
    redirect_to newsletters_path
  end

  # GET /newsletters/1/edit
  def edit
  end

  # POST /newsletters
  # POST /newsletters.json
  def create
    @newsletter = Newsletter.new(newsletter_params)

    respond_to do |format|
      if @newsletter.save
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully created.' }
        format.json { render :show, status: :created, location: @newsletter }
      else
        format.html { render :new }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsletters/1
  # PATCH/PUT /newsletters/1.json
  def update
    respond_to do |format|
      if @newsletter.update(newsletter_params)
        format.html { redirect_to @newsletter, notice: 'Newsletter was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsletter }
      else
        format.html { render :edit }
        format.json { render json: @newsletter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsletters/1
  # DELETE /newsletters/1.json
  def destroy
    @newsletter.destroy
    respond_to do |format|
      format.html { redirect_to newsletters_url, notice: 'Newsletter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsletter
      @newsletter = Newsletter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsletter_params
      params.require(:newsletter).permit(:subject, :content, :user_id)
    end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
end

app/views/newsletters/_form.html.erb
<%= form_with(model: newsletter, local: true) do |form| %>
  <% if newsletter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newsletter.errors.count, "error") %> prohibited this newsletter from being saved:</h2>

      <ul>
      <% newsletter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <i class="material-icons prefix">title</i>
    <%= form.label :subject, "Asunto", class: 'active' %>
    <%= form.text_field :subject, id: :newsletter_subject %>
  </div>

  <div style="height:30em">
    <%= form.text_area :content, id: :newsletter_content, class: 'quill_container' %>
  </div>


  <div class="field" style="display:none">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :newsletter_user_id, value: 1 %>
  </div>

  <br /> <br />
  <div class="actions center-align">
      <%= link_to 'Atrás', newsletters_path, class:"btn waves-effect waves-light" %>
      <%= form.submit 'Crear Correo', class: "btn waves-effect waves-light" %>
  </div>
<% end %>

app/views/newsletters/edit.html.erb
<section class="container">
  <div class="row">
    <h3 class="center-align">Editar Correo</h3>
    <article class="col s12">
      <%= render 'form', newsletter: @newsletter %>
    </article>
  </div>
</section>

app/views/newsletters/index.html.erb
<div class="container">
  <h2 class="center-align">Correos Masivos</h2>
</div>
<div class="divider"></div>


<div class="row">
  <div class="container">
    <% if current_user.try(:admin?) %>
      <div class="col m12">
        <h5 class="center-align">
            <%= link_to 'Nuevo Correo', new_newsletter_path, class: "btn waves-effect waves-light"%>
        </h5>
      </div>
    <% end %>

    <div class="col m6 offset-m3">

      <table class="striped">
        <thead>
          <tr>
            <th>Asunto</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @newsletters.each do |newsletter| %>
            <tr>
              <td><%= newsletter.subject %></td>
              <td><%= link_to (fa_icon "eye"), newsletter %></td>
              <td><%= link_to (fa_icon "pencil"), edit_newsletter_path(newsletter) %></td>
              <td><%= link_to (fa_icon "times"), newsletter, method: :delete, data: { confirm: '¿Esta seguro de eliminar el mensaje?' } %></td>
              <td><%= link_to (fa_icon "telegram"), deliver_newsletter_path(newsletter), data: {confirm: '¿Quiere enviar el mensaje?'}, method: :post %></td>

            </tr>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>

</div>

app/views/newsletters/new.html.erb
<section class="container">
  <div class="row">
    <h3 class="center-align">Nuevo Correo</h3>
    <article class="col s12">
      <%= render 'form', newsletter: @newsletter %>
    </article>
  </div>
</section>

app/views/newsletters/show.html.erb
<div class="container">
    <div class="row">
      <div class="col s12">
        <h5>Asunto</h5>
        <%= @newsletter.subject %>
      </div>
    </div>
    <div class="row">
      <div class="col s12">
        <h5>Mensaje </h5>
        <textarea name="name" class="quill_container">
          <%= @newsletter.content %>
          <!-- <script type="text/javascript">
            Quilljs.setDefaults( { toolbar: false });
          </script> -->
        </textarea>
        </div>
      </div>
    </div>
</div>

<div class="col s10">
  <div class="center-align">
    <%= link_to 'Atras', newsletters_path, class:"btn waves-effect waves-light" %>
    <% if current_user.try(:admin?) %>
      <%= link_to 'Editar', edit_newsletter_path(@newsletter), class:"btn waves-effect waves-light" %>
    <% end %>
  </div>
</div>