config/routes.rb
Rails.application.routes.draw do

  localized do
    # rest
    resources :censos
    resources :people
    resources :certificates
    resources :votes
    resources :candidates
    resources :elections
    resources :request_censos
    resources :contacts, only: %i[new index create]

    # routes with only a member
    resources :announcements do
      delete 'remove_olds', on: :collection
    end

    resources :events do
      delete 'remove_olds', on: :collection
    end

    # routes for events
    resources :newsletters do
      post 'deliver', on: :member
    end

    # single routes

    get 'residences/index'

    # routes with namespace
    namespace :statistics do
      get 'total', 'average', 'health', 'gender', 'health', 'censo_date', 'children'
    end

    # routes devise
    devise_for :users

    # root
    root to: 'home#index'
  end

  namespace :users do
    namespace :omniauth_callbacks do
      get 'facebook', 'google_oauth2', 'twitter'
    end
  end

  devise_scope :user do
    namespace :users do
      scope 'auth' do
        get 'facebook/callback', to: 'omniauth_callbacks#facebook'
        get 'google_oauth2/callback', to: 'omniauth_callbacks#google_oauth2'
        get 'twitter/callback', to: 'omniauth_callbacks#twitter'
      end
    end
  end
end

app/models/request_censo.rb
# == Schema Information
#
# Table name: request_censos
#
#  id           :integer          not null, primary key
#  name         :string
#  lastname     :string
#  num_document :integer
#  phone        :integer
#  address      :string
#  user_email   :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class RequestCenso < ApplicationRecord
    validates :name, :lastname, :num_document, :phone, :address, presence: true

    def self.check_user_request
        RequestCenso.find_by user_email: ("#{User.current.email}")
    end

    def self.check_data
        get_document = RequestCenso.find_by user_email: ("#{User.current.email}")
        Person.joins(:censo).where(documentPerson: get_document.num_document)
    end

    def self.check_data_two
        get_document = RequestCenso.last
        Person.joins(:censo).where(documentPerson: get_document.num_document)
    end
end

app/controllers/request_censos_controller.rb
class RequestCensosController < ApplicationController
  before_action :set_request_censo, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /request_censos
  # GET /request_censos.json
  def index
    @request_censos = RequestCenso.paginate(page: params[:page]).order(sort_column + ' ' + sort_direction)
  end

  # GET /request_censos/1
  # GET /request_censos/1.json
  def show
    if current_user.try(:admin?)
      @check_censo = RequestCenso.check_data_two
    else
      @check_censo = RequestCenso.check_data
    end
  end

  # GET /request_censos/new
  def new
    @request_censo = RequestCenso.new
    if  current_user.try(:admin?)
      @check_data = nil
    else
      @check_data = RequestCenso.check_user_request
    end
  end

  # GET /request_censos/1/edit
  def edit
  end

  # POST /request_censos
  # POST /request_censos.json
  def create
    @request_censo = RequestCenso.new(request_censo_params)

    respond_to do |format|
      if @request_censo.save
        format.html { redirect_to @request_censo, notice: 'Request censo was successfully created.' }
        format.json { render :show, status: :created, location: @request_censo }
      else
        format.html { render :new }
        format.json { render json: @request_censo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_censos/1
  # PATCH/PUT /request_censos/1.json
  def update
    respond_to do |format|
      if @request_censo.update(request_censo_params)
        format.html { redirect_to @request_censo, notice: 'Request censo was successfully updated.' }
        format.json { render :show, status: :ok, location: @request_censo }
      else
        format.html { render :edit }
        format.json { render json: @request_censo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_censos/1
  # DELETE /request_censos/1.json
  def destroy
    @request_censo.destroy
    respond_to do |format|
      format.html { redirect_to request_censos_url, notice: 'Request censo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_censo
      @request_censo = RequestCenso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_censo_params
      params.require(:request_censo).permit(:name, :lastname, :num_document, :phone, :address, :user_email)
    end

    def sortable_columns
        ['name','lastname', 'num_document', 'phone', 'direction', 'user_email']
    end
    def sort_column
      sortable_columns.include?(params[:sort]) ? params[:sort] : 'name'
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : 'asc'
    end

    def authorize_admin
     return unless !current_user.admin?
     redirect_to root_path, alert: 'Admins only!'
   end
end

app/helpers/request_censos_helper.rb
module RequestCensosHelper
    def sortable(column, title = nil)
      title ||= column.titleize
      css_class = column == sort_column ? "current #{sort_direction}" : nil
      direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
      link_to title, {:sort => column, :direction => direction}, {:class => css_class}
    end
end

app/views/request_censos/_form.html.erb
<%= form_with(model: request_censo, local: true) do |form| %>
  <% if request_censo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request_censo.errors.count, "error") %> prohibited this request_censo from being saved:</h2>

      <ul>
      <% request_censo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="input-field">
     <i class="material-icons prefix">account_circle</i>
    <%= form.label :name, "Nombre" %>
    <%= form.text_field :name, id: :request_censo_name %>
  </div>

  <div class="input-field">
     <i class=" prefix"></i>
    <%= form.label :lastname, "Apellido" %>
    <%= form.text_field :lastname, id: :request_censo_lastname %>
  </div>


  <div class="input-field">
     <i class=" prefix"></i>
    <%= form.label :num_document, "Número de documento"%>
    <%= form.number_field :num_document, id: :request_censo_num_document %>
  </div>

  <div class="input-field">
     <i class="material-icons prefix">phone</i>
    <%= form.label :phone, "Telefono" %>
    <%= form.number_field :phone, id: :request_censo_phone %>
  </div>

  <div class="input-field">
     <i class="material-icons prefix">home</i>
    <%= form.label :address, "Dirección residencia"%>
    <%= form.text_field :address, id: :request_censo_address %>
  </div>
 <% unless current_user.try(:admin?) %>
  <div class="input-field">
     <i class="material-icons prefix">email</i>
    <%=  form.email_field :user_email, id: :request_censo_address, :value => current_user.email, readonly: true %>
    <div class="actions center-align">
     <%= form.submit 'Solicitar', class: "btn waves-effect waves-light" %>
   </div>
  </div>
 <%else%>
     <div class="input-field">
        <i class="material-icons prefix">email</i>
       <%= form.label :user_email, "Correo"%>
       <%= form.text_field :user_email, id: :request_censo_user_email %>
     </div>
     <div class="actions center-align">
      <%= form.submit 'Agendar', class: "btn waves-effect waves-light" %>
    </div>
  <% end %>
<%end%>

app/views/request_censos/edit.html.erb
<%= render 'form', request_censo: @request_censo %>

<%= link_to 'Show', @request_censo %> |
<%= link_to 'Back', request_censos_path %>

app/views/request_censos/index.html.erb
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>

    <div class="container">
      <h2 class="center-align">Solicitudes de censo</h2>
    </div>
    <div class="divider"></div>
    <div class="container">
      <div class="row">
        <div class="col s12">
          <table class="striped">
            <thead>
              <tr>
                <th><%= sortable 'name', "Nombre"%></th>
                <th><%= sortable 'lastname', "Apellido" %></th>
                <th><%= sortable 'num_document', "Número de documento" %></th>
                <th><%= sortable 'phone', "Telefono" %></th>
                <th><%= sortable 'address', "Direccion" %></th>
                <th><%= sortable 'user_email', "email" %></th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
                <% @request_censos.each do |request_censo| %>
                  <tr>
                    <td><%= request_censo.name %></td>
                    <td><%= request_censo.lastname %></td>
                    <td><%= request_censo.num_document %></td>
                    <td><%= request_censo.phone %></td>
                    <td><%= request_censo.address %></td>
                    <td><%= request_censo.user_email %></td>
                    
                    <td><%= link_to (fa_icon "times"), request_censo, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
                  </tr>
                <% end %>

            </tbody>
          </table>
        </div>
      </div>

        <div class="row">
          <h5 class="center-align">
            <%= link_to 'Agendar solicitud', new_request_censo_path, class: "btn waves-effect waves-light" %>
          </h5>
        </div>
    </div>


    <% end %>
    <% end %>

    <%= will_paginate @collection,
        class: 'apple_pagination',
        previous_label: '&#8592;<strong> Anterior',
        next_label: 'Siguiente &#8594;'
    %>

app/views/request_censos/new.html.erb
<% if user_signed_in? %>
  <% unless  @check_data == nil%>
      <section class="container">
        <div class="row card-form">
          <article class="col s8 offset-s2 z-depth-5">
            <div class="card-form">
              <h3 class="center-align">Solicitud de censo</h3>
                <h6 class="center-align">Usted ya tiene una solicitud agendada</h6>
            </div>

          </article>
          </div>
          <div class=" row col m10 center-align">
              <%= link_to 'Contactese con el administrador', new_contact_path, class:"col m6"%>
              <%= link_to 'Volver al inicio', root_path, class:" col m6" %>

          </div>

      </section>

    <% else%>
        <section class="container">
          <div class="row card-form">
            <article class="col s8 offset-s2 z-depth-5">
              <div class="card-form">
                <h3 class="center-align">Solicitud de censo</h3>
                <%= render 'form', request_censo: @request_censo %>
              </div>
            </article>
            </div>
        </section>

    <% end%>
    <% end%>

app/views/request_censos/show.html.erb
<% if user_signed_in? %>
    <% if  @check_data == nil%>
        <section class="container">
          <div class="row card-form">
            <article class="col s8 offset-s2 z-depth-5">
              <div class="card-form">
                  <h6 class="center-align"> Ya se encuentra en el censo</h6>
              </div>
               <%= link_to 'Volver al inicio', root_path %>
            </article>
        </section>
          <%= link_to 'Atras', new_certificate_path %>

    <% else %>
    <div class="container">
      <!-- <div class="col s10"> -->
        <div class="row">
          <div class="col s6">
            <p class="right-align">
              <h5> Nombre </h5>
              <%= @request_censo.name  %>
            </p>
          </div>

          <div class="col s6">
            <p class="left-align">
              <h5> Apellido </h5>
              <%= @request_censo.lastname %>
            </p>
          </div>
        </div>

        <div class="row">
          <div class="col s10 offset-s1">
            <p>
              <h5> Número de documento </h5>
                <%= @request_censo.num_document %>
            </p>
          </div>
        </div>

        <div class="row">
          <div class="col s10 offset-s1">
            <p>
              <h5> Telefono </h5>
                <%= @request_censo.phone %>
            </p>
          </div>
        </div>

        <div class="row">
          <div class="col s10 offset-s1">
            <p>
              <h5> Dirección </h5>
                 <%= @request_censo.address%>
            </p>
          </div>
        </div>


    </div>

    <div class="col s10">
      <div class="center-align">
        <%= link_to 'Ir al inicio', root_path, class:"btn waves-effect waves-light" %>
        <% if current_user.try(:admin?) %>
            <%= link_to 'Atrás', request_censos_path, class:"btn waves-effect waves-light" %>
        <%end%>

      </div>
    </div>

    <% end %>


<%end%>