config/routes.rb
Rails.application.routes.draw do

  localized do
    # rest
    resources :censos
    resources :people
    resources :certificates
    resources :votes
    resources :candidates
    resources :elections
    resources :request_censos
    resources :contacts, only: %i[new index create]

    # routes with only a member
    resources :announcements do
      delete 'remove_olds', on: :collection
    end

    resources :events do
      delete 'remove_olds', on: :collection
    end

    # routes for events
    resources :newsletters do
      post 'deliver', on: :member
    end

    # single routes

    get 'residences/index'

    # routes with namespace
    namespace :statistics do
      get 'total', 'average', 'health', 'gender', 'health', 'censo_date', 'children'
    end

    # routes devise
    devise_for :users

    # root
    root to: 'home#index'
  end

  namespace :users do
    namespace :omniauth_callbacks do
      get 'facebook', 'google_oauth2', 'twitter'
    end
  end

  devise_scope :user do
    namespace :users do
      scope 'auth' do
        get 'facebook/callback', to: 'omniauth_callbacks#facebook'
        get 'google_oauth2/callback', to: 'omniauth_callbacks#google_oauth2'
        get 'twitter/callback', to: 'omniauth_callbacks#twitter'
      end
    end
  end
end

app/models/certificate.rb
# == Schema Information
#
# Table name: certificates
#
#  id             :integer          not null, primary key
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  documentPerson :integer
#  email          :string
#

# certificate_model
class Certificate < ApplicationRecord

  validates :documentPerson, presence: true

  def self.data_person
    certi_last = Certificate.last
    User.select("\"documentPerson\"", "firstname", "lastname", "\"documentType\"").joins(:person).where("\"isCensus\"=? and \"documentPerson\" =?", "t", certi_last.documentPerson)

  end

  def self.check_censo
      get_document_cert = Certificate.where(["email = ?", ("#{User.current.email}")]).last
      document= get_document_cert.documentPerson
      User.select("\"documentPerson\"", "firstname", "lastname", "\"documentType\"").joins(:person).where("email= ? and \"isCensus\"=? and \"documentPerson\" =?",("#{User.current.email}"), "t", document)
  end




end

app/controllers/certificates_controller.rb
# certificate_controller
class CertificatesController < ApplicationController
  before_action :set_certificate, only: [:show, :edit, :update, :destroy]

  # GET /certificates
  # GET /certificates.json
  def index
    @certificates = Certificate.all
  end

  # GET /certificates/1
  # GET /certificates/1.json
  def show
    if current_user.try(:admin?)
      @dat = Certificate.data_person
    else
      @dat = Certificate.check_censo
    end
    respond_to do |format|
      format.html
      format.json { render json: @certificates }
      format.pdf {render template: 'certificates/certificate', pdf:'certificado'}
    end
  end

  # GET /certificates/new
  def new
    @certificate = Certificate.new
  end

  # GET /certificates/1/edit
  def edit
  end

  # POST /certificates
  # POST /certificates.json
  def create
    @certificate = Certificate.new(certificate_params)
    respond_to do |format|
      if @certificate.save
        format.html { redirect_to @certificate, notice: 'Certificate was successfully created.' }
        format.json { render :show, status: :created, location: @certificate }
      else
        format.html { render :new }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certificates/1
  # PATCH/PUT /certificates/1.json
  def update
    respond_to do |format|
      if @certificate.update(certificate_params)
        format.html { redirect_to @certificate, notice: 'Certificate was successfully updated.' }
        format.json { render :show, status: :ok, location: @certificate }
      else
        format.html { render :edit }
        format.json { render json: @certificate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certificates/1
  # DELETE /certificates/1.json
  def destroy
    @certificate.destroy
    respond_to do |format|
      format.html { redirect_to certificates_url, notice: 'Certificate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_certificate
    @certificate = Certificate.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def certificate_params
    params.require(:certificate).permit(:documentPerson, :email)
  end

end

app/helpers/certificates_helper.rb
module CertificatesHelper
end

app/views/certificates/_form.html.erb
<%= form_with(model: certificate, local: true) do |form| %>
  <% if certificate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(certificate.errors.count, "error") %> prohibited this certificate from being saved:</h2>

      <ul>
      <% certificate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-field">
    <i class="material-icons prefix">chevron_right</i>
    <%= form.label :documentPerson, "Ingrese  Documento" %>
    <%= form.number_field :documentPerson, id: :certificate_documentPerson %>
  </div>

<% if current_user.try(:admin?) %>
      <div class="actions center-align">
        <%= button_tag type: 'submit', class: "waves-effect waves-light btn" do %>
            <h6>Buscar      <i class="material-icons">search</i> </h6>
        <% end %>

      </div>
 <% else %>
     <div class="input-field">
        <i class="material-icons prefix">email</i>
       <%=  form.email_field :email, id: :certificate_email, :value => current_user.email, readonly: true %>
    </div>
       <div class="actions center-align">
        <%= form.submit 'Solicitar', class: "btn waves-effect waves-light" %>
      </div>

    <% end %>


<% end %>

app/views/certificates/certificate.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= wicked_pdf_stylesheet_link_tag 'pdf'%>
    <meta charset="UTF-8">
  </head>
  <body>
      <br>
    <div class="logo">
      <%= wicked_pdf_image_tag 'backgrounds/Logo-Aico.png'%>
    </div>
    <div class="title">


      <blockquote>
        La honorable corporacion del cabildo indigena del pueblo de los pastos en uso de sus
        facultades legales que le confiere el derecho mayor, la ley de origen, la ley natural,
        el convenio 169 de la OIT, la ley 89 de 1989, la constitucion politica de 1991, la declaracion
        de las naciones unidas sobre los derechos de los pueblos indigenas, la ley 21 de 1991,
        el decreto 543 del 2011 que adopta la politica publica para los pueblos
        indigenas en Bogotá D.C, DECRETO 612 de 2015, "por el cual se crea el consejo consultivo
        y de concertacion para los pueblos indigenas en Bogotá D.C" y demás normas que
        defienen los derechos de los pueblos indigenas en Colombia
      </blockquote>
      <br>
      <br>
      <h5>CERTIFICA</h5>

    </div>

    <% time = Time.new%>
    <div class="text-body">

        <p> Que el indigena, <%= @dat.first.firstname %>   <%=@dat.first.lastname%>, identificado con numero de identificacion
        <%= @dat.first.documentType %>. <%= @dat.first.documentPerson %>, hacen parte de la comunidad
        del cabildo indigena del pueblo de los pastos de Bogotá, por lo tanto, se encuentran afiliados
        al censo interno y cumplen a sus usos y costumbres con los programas y actividades del cabildo.
        </p>
        <p>Dado en Bogota el <%= time.day %>-<%= time.month %>-<%= time.year %>, dirigida a quien corresponda.

    </div>

    <div class="firm">
        <p>Maria de Jesus Erira C.</p>
        <p>Gobernadora</p>
        <p>Cabildo indigena de los pastos</p>

    </div>


  </body>
</html>

app/views/certificates/edit.html.erb
<h1>Editing Certificate</h1>

<%= render 'form', certificate: @certificate %>

<%= link_to 'Show', @certificate %> |
<%= link_to 'Back', certificates_path %>

app/views/certificates/new.html.erb
<% if user_signed_in? %>

    <section class="container">
      <div class="row">
        <h3 class="center-align">Certificado</h3>
        <article class="col s6 offset-s3">
          <%= render 'form', certificate: @certificate %>
        </article>
      </h3>
    </section>  
<%end%>

app/views/certificates/show.html.erb
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <% if @dat.empty?%>

        <div class="container">
          <div class="row">
            <div class="col m3"></div>
            <div class="col m7">
              <h5 class="center-align">
                Esta persona  NO se encuentra en el censo
            </h5>
            </div>
            <div class="row">
                <div class="col m3"></div>
                <div class="col m7">
                  <h4 class="center-align ">
                      <%= link_to 'Atras', new_certificate_path, class: "btn waves-effect waves-light" %>
                  </h4>
                </div>
            </div>
            </div>
            </div>




    <% else %>
      <div class="container">
          <div class="row">
              <div class="col m3"></div>
              <div class="col m7">
                <h5 class="center-align">
                    La persona identificada con <%= @dat.first.documentPerson%> se encuentra censada    </h5>
              </div>

              <div class="row">
                  <div class="col m3"></div>
                  <div class="col m7">
                    <h4 class="center-align ">
                         <%= link_to  'Descarga PDF',  certificate_path(format: :pdf), target:"_blank", class: "btn waves-effect waves-light" %>

                    </h4>
                  </div>
              </div>

        </div>
      </div>
    <% end %>

    <% else %>

        <% if @dat.empty?%>

            <div class="container">
              <div class="row">
                <div class="col m3"></div>
                <div class="col m7">
                  <h5 class="center-align">
                    Ud NO se encuentra censado, su número de documento no corresponde con el email
                    que registra en el censo
                </h5>
                </div>
                </div>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col m3"></div>
                        <div class="col m7">
                            <h4 class="center-align">
                                <%= link_to 'Solicitar Censo', new_request_censo_path, class: "btn waves-effect waves-light"%>
                            </h4>
                       </div>

                    </div>

                </div>

        <% else %>

        <div class="container">
          <div class="row">
            <div class="col m3"></div>
            <div class="col m7">
              <h5 class="center-align">
                Click en el boton para descargar certificado PDF
            </h5>
            </div>
            </div>

          <div class="container">
                  <div class="row">
                      <div class="col m3"></div>
                      <div class="col m7">
                        <h4 class="center-align ">
                             <%= link_to  'Descarga PDF',  certificate_path(format: :pdf), target:"_blank", class: "btn waves-effect waves-light" %>
                        </h4>
                      </div>
                  </div>
          </div>
        <% end %>



    <%end%>
<%end%>