config/routes.rb
Rails.application.routes.draw do

  localized do
    # rest
    resources :censos
    resources :people
    resources :certificates
    resources :votes
    resources :candidates
    resources :elections
    resources :request_censos
    resources :contacts, only: %i[new index create]

    # routes with only a member
    resources :announcements do
      delete 'remove_olds', on: :collection
    end

    resources :events do
      delete 'remove_olds', on: :collection
    end

    # routes for events
    resources :newsletters do
      post 'deliver', on: :member
    end

    # single routes

    get 'residences/index'

    # routes with namespace
    namespace :statistics do
      get 'total', 'average', 'health', 'gender', 'health', 'censo_date', 'children'
    end

    # routes devise
    devise_for :users

    # root
    root to: 'home#index'
  end

  namespace :users do
    namespace :omniauth_callbacks do
      get 'facebook', 'google_oauth2', 'twitter'
    end
  end

  devise_scope :user do
    namespace :users do
      scope 'auth' do
        get 'facebook/callback', to: 'omniauth_callbacks#facebook'
        get 'google_oauth2/callback', to: 'omniauth_callbacks#google_oauth2'
        get 'twitter/callback', to: 'omniauth_callbacks#twitter'
      end
    end
  end
end

app/models/residence.rb
# == Schema Information
#
# Table name: residences
#
#  id           :integer          not null, primary key
#  address      :string
#  phone        :integer
#  neighborhood :string
#  locality     :string
#  latitude     :float
#  longitude    :float
#  person_id    :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Residence < ApplicationRecord
  belongs_to :person
  geocoded_by :address
  after_validation :geocode

  validates :address, :phone, :neighborhood, :locality, :latitude, presence: true

  def self.data_gps
    residences = Residence.all
    Gmaps4rails.build_markers(residences) do |residence, marker|
      marker.lat residence.latitude
      marker.lng residence.longitude
      marker.infowindow residence.neighborhood
    end
  end
end

app/controllers/residences_controller.rb
# residences_controller
class ResidencesController < ApplicationController
  before_action :set_residence, only: [:show, :edit, :update, :destroy]

  # GET /residences
  # GET /residences.json
  def index
    @hash = Residence.data_gps
  end

  # GET /residences/1
  # GET /residences/1.json
  def show
  end

  # GET /residences/new
  def new
    @residence = Residence.new
  end

  # GET /residences/1/edit
  def edit
  end

  # POST /residences
  # POST /residences.json
  def create
    @residence = Residence.new(residence_params)

    respond_to do |format|
      if @residence.save
        format.html { redirect_to @residence, notice: 'Residence was successfully created.' }
        format.json { render :show, status: :created, location: @residence }
      else
        format.html { render :new }
        format.json { render json: @residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /residences/1
  # PATCH/PUT /residences/1.json
  def update
    respond_to do |format|
      if @residence.update(residence_params)
        format.html { redirect_to @residence, notice: 'Residence was successfully updated.' }
        format.json { render :show, status: :ok, location: @residence }
      else
        format.html { render :edit }
        format.json { render json: @residence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residences/1
  # DELETE /residences/1.json
  def destroy
    @residence.destroy
    respond_to do |format|
      format.html { redirect_to residences_url, notice: 'Residence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_residence
    @residence = Residence.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def residence_params
    params.require(:residence).permit(:address, :phone, :neighborhood, :locality, :latitude, :longitude, :person_id)
  end
end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/views/residences/_form.html.erb
<%= form_with(model: residence, local: true) do |form| %>
  <% if residence.errors.any? %>
    <div id="error_explanation">
      <h2><%= residence.errors.count %><%= residence.errors.count == 1 ? ' error' : ' errores' %></h2>

      <ul>
      <% residence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <i class="material-icons prefix">home</i>
    <%= form.label :address, 'Dirección', class: 'active' %>
    <%= form.text_field  :address, id: :residence_address, class: "materialize-textarea" %>
  </div>

  <div class="input-field">
    <i class="material-icons prefix">phone</i>
    <%= form.label :phone, 'Telefono', class: 'active' %>
    <%= form.number_field :phone, id: :residence_phone %>
  </div>

  <div class="input-field">
    <i class="material-icons prefix">place</i>
    <%= form.label :neighborhood, 'Barrio', class: 'active' %>
    <%= form.text_field :neighborhood, id: :residence_neighborhood %>
  </div>

  <div class="input-field">
    <i class="material-icons prefix">place</i>
    <%= form.label :locality, 'Localidad', class: 'active' %>
    <%= form.text_field :locality, id: :residence_locality %>
  </div>

  <div class="actions center-align">
    <%= form.submit 'Siguiente', class: 'waves-effect waves-light btn' %>
  </div>
<% end %>

app/views/residences/edit.html.erb
<div class="container">
  <div class="row">
    <h1 class="center-align">Edite su residencia</h1>
  </div>
  <div class="row">
    <div class="col s8 offset-s2 z-depth-5">
      <div class="card-form">
        <%= render 'form', residence: @residence %>
      </div>
    </div>
  </div>
</div>

app/views/residences/index.html.erb
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
<script src="//maps.google.com/maps/api/js?key=AIzaSyBte7uGJfrDBm71LBz2Aohyhku5y-HSWIo"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<h1 class="center-align">Residencias</h1>

<div class="container">
  <div class="row">
    <div class="col m1"></div>
    <div class="center_align">
      <div class="responsive-img">
        <div id="map" style='width: 100%; height: 500px;'></div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>


  <% end %>
<% end %>

app/views/residences/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="center-align">Residencia</h1>
  </div>

  <div class="row">
    <div class="col s8 offset-s2 z-depth-5">
      <div class="card-form">
        <%= render 'form', residence: @residence %>
      </div>
    </div>
  </div>
</div>

app/views/residences/show.html.erb
<div class="container">
  <div class="row">
    <h2 class="center-align">Se llenaron los siguientes datos</h2>
  </div>

  <div class="row">
    <div class="col s8 offset-s2">
      <table class="bordered centered highlight responsive-table z-depth-5">
        <tbody>
          <tr>
            <td><strong>Dirrección:</strong></td>
            <td><%= @residence.address %></td>
          </tr>
          <tr>
            <td><strong>Telefono:</strong></td>
            <td><%= @residence.phone %></td>
          </tr>
          <tr>
            <td><strong>Barrio:</strong></td>
            <td><%= @residence.neighborhood %></td>
          </tr>
          <tr>
            <td><strong>Localidad:</strong></td>
            <td><%= @residence.locality %></td>
          </tr>
        </tbody>
    </div>
  </div>

  </table>

  <div class="center-align">
    <%= link_to 'Editar', edit_residence_path(@residence), class: 'waves-effect waves-light btn-large' %>
    <%= link_to 'Siguiente', new_censo_path, class: 'waves-effect waves-light btn-large' %>
  </div>



</div>